Imports System
Imports System.Collections.Generic
Imports System.Data
Imports System.Data.SqlClient
Imports System.ComponentModel
Namespace SIS.PAK
  <DataObject()> _
  Partial Public Class pakTCPOLRD
    Private Shared _RecordCount As Integer
    Private _SerialNo As Int32 = 0
    Private _ItemNo As Int32 = 0
    Private _UploadNo As Int32 = 0
    Private _DocSerialNo As Int32 = 0
    Private _DocumentID As String = ""
    Private _DocumentRev As String = ""
    Private _DocumentDescription As String = ""
    Private _ReceiptNo As String = ""
    Private _RevisionNo As String = ""
    Private _FileName As String = ""
    Private _DiskFileName As String = ""
    Private _ERPDocSerialNo As String = ""
    Private _PAK_PO1_PODescription As String = ""
    Private _PAK_POLine2_ItemCode As String = ""
    Private _PAK_POLineRec3_UploadNo As Int32 = 0
    Private _FK_PAK_POLineRecDoc_SerialNo As SIS.PAK.pakPO = Nothing
    Private _FK_PAK_POLineRecDoc_ItemNo As SIS.PAK.pakTCPOL = Nothing
    Private _FK_PAK_POLineRecDoc_UploadNo As SIS.PAK.pakTCPOLR = Nothing
    Public Property AutoGenerated As Boolean = False
    Public ReadOnly Property ForeColor() As System.Drawing.Color
      Get
        Dim mRet As System.Drawing.Color = Drawing.Color.Blue
        Try
          mRet = GetColor()
        Catch ex As Exception
        End Try
        Return mRet
      End Get
    End Property
    Public ReadOnly Property Visible() As Boolean
      Get
        Dim mRet As Boolean = True
        Try
          mRet = GetVisible()
        Catch ex As Exception
        End Try
        Return mRet
      End Get
    End Property
    Public ReadOnly Property Enable() As Boolean
      Get
        Dim mRet As Boolean = True
        Try
          mRet = GetEnable()
        Catch ex As Exception
        End Try
        Return mRet
      End Get
    End Property
    Public Property SerialNo() As Int32
      Get
        Return _SerialNo
      End Get
      Set(ByVal value As Int32)
        _SerialNo = value
      End Set
    End Property
    Public Property ItemNo() As Int32
      Get
        Return _ItemNo
      End Get
      Set(ByVal value As Int32)
        _ItemNo = value
      End Set
    End Property
    Public Property UploadNo() As Int32
      Get
        Return _UploadNo
      End Get
      Set(ByVal value As Int32)
        _UploadNo = value
      End Set
    End Property
    Public Property DocSerialNo() As Int32
      Get
        Return _DocSerialNo
      End Get
      Set(ByVal value As Int32)
        _DocSerialNo = value
      End Set
    End Property
    Public Property DocumentID() As String
      Get
        Return _DocumentID
      End Get
      Set(ByVal value As String)
         If Convert.IsDBNull(Value) Then
           _DocumentID = ""
         Else
           _DocumentID = value
         End If
      End Set
    End Property
    Public Property DocumentRev() As String
      Get
        Return _DocumentRev
      End Get
      Set(ByVal value As String)
         If Convert.IsDBNull(Value) Then
           _DocumentRev = ""
         Else
           _DocumentRev = value
         End If
      End Set
    End Property
    Public Property DocumentDescription() As String
      Get
        Return _DocumentDescription
      End Get
      Set(ByVal value As String)
         If Convert.IsDBNull(Value) Then
           _DocumentDescription = ""
         Else
           _DocumentDescription = value
         End If
      End Set
    End Property
    Public Property ReceiptNo() As String
      Get
        Return _ReceiptNo
      End Get
      Set(ByVal value As String)
        _ReceiptNo = value
      End Set
    End Property
    Public Property RevisionNo() As String
      Get
        Return _RevisionNo
      End Get
      Set(ByVal value As String)
        _RevisionNo = value
      End Set
    End Property
    Public Property FileName() As String
      Get
        Return _FileName
      End Get
      Set(ByVal value As String)
         If Convert.IsDBNull(Value) Then
           _FileName = ""
         Else
           _FileName = value
         End If
      End Set
    End Property
    Public Property DiskFileName() As String
      Get
        Return _DiskFileName
      End Get
      Set(ByVal value As String)
        If Convert.IsDBNull(Value) Then
          _DiskFileName = ""
        Else
          _DiskFileName = value
        End If
      End Set
    End Property
    'ERPDocSerialNo
    Public Property ERPDocSerialNo() As String
      Get
        Return _ERPDocSerialNo
      End Get
      Set(ByVal value As String)
        If Convert.IsDBNull(value) Then
          _ERPDocSerialNo = ""
        Else
          _ERPDocSerialNo = value
        End If
      End Set
    End Property

    Public Property PAK_PO1_PODescription() As String
      Get
        Return _PAK_PO1_PODescription
      End Get
      Set(ByVal value As String)
         If Convert.IsDBNull(Value) Then
           _PAK_PO1_PODescription = ""
         Else
           _PAK_PO1_PODescription = value
         End If
      End Set
    End Property
    Public Property PAK_POLine2_ItemCode() As String
      Get
        Return _PAK_POLine2_ItemCode
      End Get
      Set(ByVal value As String)
         If Convert.IsDBNull(Value) Then
           _PAK_POLine2_ItemCode = ""
         Else
           _PAK_POLine2_ItemCode = value
         End If
      End Set
    End Property
    Public Property PAK_POLineRec3_UploadNo() As Int32
      Get
        Return _PAK_POLineRec3_UploadNo
      End Get
      Set(ByVal value As Int32)
        _PAK_POLineRec3_UploadNo = value
      End Set
    End Property
    Public Readonly Property DisplayField() As String
      Get
        Return "" & _DocumentID.ToString.PadRight(32, " ")
      End Get
    End Property
    Public Readonly Property PrimaryKey() As String
      Get
        Return _SerialNo & "|" & _ItemNo & "|" & _UploadNo & "|" & _DocSerialNo
      End Get
    End Property
    Public Shared Property RecordCount() As Integer
      Get
        Return _RecordCount
      End Get
      Set(ByVal value As Integer)
        _RecordCount = value
      End Set
    End Property
    Public Class PKpakTCPOLRD
      Private _SerialNo As Int32 = 0
      Private _ItemNo As Int32 = 0
      Private _UploadNo As Int32 = 0
      Private _DocSerialNo As Int32 = 0
      Public Property SerialNo() As Int32
        Get
          Return _SerialNo
        End Get
        Set(ByVal value As Int32)
          _SerialNo = value
        End Set
      End Property
      Public Property ItemNo() As Int32
        Get
          Return _ItemNo
        End Get
        Set(ByVal value As Int32)
          _ItemNo = value
        End Set
      End Property
      Public Property UploadNo() As Int32
        Get
          Return _UploadNo
        End Get
        Set(ByVal value As Int32)
          _UploadNo = value
        End Set
      End Property
      Public Property DocSerialNo() As Int32
        Get
          Return _DocSerialNo
        End Get
        Set(ByVal value As Int32)
          _DocSerialNo = value
        End Set
      End Property
    End Class
    Public ReadOnly Property FK_PAK_POLineRecDoc_SerialNo() As SIS.PAK.pakPO
      Get
        If _FK_PAK_POLineRecDoc_SerialNo Is Nothing Then
          _FK_PAK_POLineRecDoc_SerialNo = SIS.PAK.pakPO.pakPOGetByID(_SerialNo)
        End If
        Return _FK_PAK_POLineRecDoc_SerialNo
      End Get
    End Property
    Public ReadOnly Property FK_PAK_POLineRecDoc_ItemNo() As SIS.PAK.pakTCPOL
      Get
        If _FK_PAK_POLineRecDoc_ItemNo Is Nothing Then
          _FK_PAK_POLineRecDoc_ItemNo = SIS.PAK.pakTCPOL.pakTCPOLGetByID(_SerialNo, _ItemNo)
        End If
        Return _FK_PAK_POLineRecDoc_ItemNo
      End Get
    End Property
    Public ReadOnly Property FK_PAK_POLineRecDoc_UploadNo() As SIS.PAK.pakTCPOLR
      Get
        If _FK_PAK_POLineRecDoc_UploadNo Is Nothing Then
          _FK_PAK_POLineRecDoc_UploadNo = SIS.PAK.pakTCPOLR.pakTCPOLRGetByID(_SerialNo, _ItemNo, _UploadNo)
        End If
        Return _FK_PAK_POLineRecDoc_UploadNo
      End Get
    End Property
    <DataObjectMethod(DataObjectMethodType.Select)> _
    Public Shared Function pakTCPOLRDSelectList(ByVal OrderBy As String) As List(Of SIS.PAK.pakTCPOLRD)
      Dim Results As List(Of SIS.PAK.pakTCPOLRD) = Nothing
      Using Con As SqlConnection = New SqlConnection(SIS.SYS.SQLDatabase.DBCommon.GetConnectionString())
        Using Cmd As SqlCommand = Con.CreateCommand()
          Cmd.CommandType = CommandType.StoredProcedure
          Cmd.CommandText = "sppakTCPOLRDSelectList"
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@LoginID", SqlDbType.NvarChar, 9, HttpContext.Current.Session("LoginID"))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@OrderBy", SqlDbType.NVarChar, 50, OrderBy)
          Cmd.Parameters.Add("@RecordCount", SqlDbType.Int)
          Cmd.Parameters("@RecordCount").Direction = ParameterDirection.Output
          _RecordCount = -1
          Results = New List(Of SIS.PAK.pakTCPOLRD)()
          Con.Open()
          Dim Reader As SqlDataReader = Cmd.ExecuteReader()
          While (Reader.Read())
            Results.Add(New SIS.PAK.pakTCPOLRD(Reader))
          End While
          Reader.Close()
          _RecordCount = Cmd.Parameters("@RecordCount").Value
        End Using
      End Using
      Return Results
    End Function
    <DataObjectMethod(DataObjectMethodType.Select)> _
    Public Shared Function pakTCPOLRDGetNewRecord() As SIS.PAK.pakTCPOLRD
      Return New SIS.PAK.pakTCPOLRD()
    End Function
    <DataObjectMethod(DataObjectMethodType.Select)> _
    Public Shared Function pakTCPOLRDGetByID(ByVal SerialNo As Int32, ByVal ItemNo As Int32, ByVal UploadNo As Int32, ByVal DocSerialNo As Int32) As SIS.PAK.pakTCPOLRD
      Dim Results As SIS.PAK.pakTCPOLRD = Nothing
      Using Con As SqlConnection = New SqlConnection(SIS.SYS.SQLDatabase.DBCommon.GetConnectionString())
        Using Cmd As SqlCommand = Con.CreateCommand()
          Cmd.CommandType = CommandType.StoredProcedure
          Cmd.CommandText = "sppakTCPOLRDSelectByID"
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@SerialNo",SqlDbType.Int,SerialNo.ToString.Length, SerialNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@ItemNo",SqlDbType.Int,ItemNo.ToString.Length, ItemNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@UploadNo",SqlDbType.Int,UploadNo.ToString.Length, UploadNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@DocSerialNo",SqlDbType.Int,DocSerialNo.ToString.Length, DocSerialNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@LoginID", SqlDbType.NvarChar, 9, HttpContext.Current.Session("LoginID"))
          Con.Open()
          Dim Reader As SqlDataReader = Cmd.ExecuteReader()
          If Reader.Read() Then
            Results = New SIS.PAK.pakTCPOLRD(Reader)
          End If
          Reader.Close()
        End Using
      End Using
      Return Results
    End Function
    <DataObjectMethod(DataObjectMethodType.Select)> _
    Public Shared Function pakTCPOLRDSelectList(ByVal StartRowIndex As Integer, ByVal MaximumRows As Integer, ByVal OrderBy As String, ByVal SearchState As Boolean, ByVal SearchText As String, ByVal SerialNo As Int32, ByVal ItemNo As Int32, ByVal UploadNo As Int32) As List(Of SIS.PAK.pakTCPOLRD)
      Dim Results As List(Of SIS.PAK.pakTCPOLRD) = Nothing
      Using Con As SqlConnection = New SqlConnection(SIS.SYS.SQLDatabase.DBCommon.GetConnectionString())
        Using Cmd As SqlCommand = Con.CreateCommand()
          Cmd.CommandType = CommandType.StoredProcedure
          If SearchState Then
            Cmd.CommandText = "sppakTCPOLRDSelectListSearch"
            SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@KeyWord", SqlDbType.NVarChar, 250, SearchText)
          Else
            Cmd.CommandText = "sppakTCPOLRDSelectListFilteres"
            SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@Filter_SerialNo",SqlDbType.Int,10, IIf(SerialNo = Nothing, 0,SerialNo))
            SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@Filter_ItemNo",SqlDbType.Int,10, IIf(ItemNo = Nothing, 0,ItemNo))
            SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@Filter_UploadNo",SqlDbType.Int,10, IIf(UploadNo = Nothing, 0,UploadNo))
          End If
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@StartRowIndex", SqlDbType.Int, -1, StartRowIndex)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@MaximumRows", SqlDbType.Int, -1, MaximumRows)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@LoginID", SqlDbType.NvarChar, 9, HttpContext.Current.Session("LoginID"))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@OrderBy", SqlDbType.NVarChar, 50, OrderBy)
          Cmd.Parameters.Add("@RecordCount", SqlDbType.Int)
          Cmd.Parameters("@RecordCount").Direction = ParameterDirection.Output
          _RecordCount = -1
          Results = New List(Of SIS.PAK.pakTCPOLRD)()
          Con.Open()
          Dim Reader As SqlDataReader = Cmd.ExecuteReader()
          While (Reader.Read())
            Results.Add(New SIS.PAK.pakTCPOLRD(Reader))
          End While
          Reader.Close()
          _RecordCount = Cmd.Parameters("@RecordCount").Value
        End Using
      End Using
      Return Results
    End Function
    Public Shared Function pakTCPOLRDSelectCount(ByVal SearchState As Boolean, ByVal SearchText As String, ByVal SerialNo As Int32, ByVal ItemNo As Int32, ByVal UploadNo As Int32) As Integer
      Return _RecordCount
    End Function
      'Select By ID One Record Filtered Overloaded GetByID
    <DataObjectMethod(DataObjectMethodType.Select)> _
    Public Shared Function pakTCPOLRDGetByID(ByVal SerialNo As Int32, ByVal ItemNo As Int32, ByVal UploadNo As Int32, ByVal DocSerialNo As Int32, ByVal Filter_SerialNo As Int32, ByVal Filter_ItemNo As Int32, ByVal Filter_UploadNo As Int32) As SIS.PAK.pakTCPOLRD
      Return pakTCPOLRDGetByID(SerialNo, ItemNo, UploadNo, DocSerialNo)
    End Function
    <DataObjectMethod(DataObjectMethodType.Insert, True)> _
    Public Shared Function pakTCPOLRDInsert(ByVal Record As SIS.PAK.pakTCPOLRD) As SIS.PAK.pakTCPOLRD
      Dim _Rec As SIS.PAK.pakTCPOLRD = SIS.PAK.pakTCPOLRD.pakTCPOLRDGetNewRecord()
      With _Rec
        .SerialNo = Record.SerialNo
        .ItemNo = Record.ItemNo
        .UploadNo = Record.UploadNo
        .DocumentID = Record.DocumentID
        .DocumentRev = Record.DocumentRev
        .DocumentDescription = Record.DocumentDescription
        .ReceiptNo = Record.ReceiptNo
        .RevisionNo = Record.RevisionNo
        .FileName = Record.FileName
        .DiskFileName = Record.DiskFileName
        .ERPDocSerialNo = Record.ERPDocSerialNo
        .AutoGenerated = Record.AutoGenerated
      End With
      Return SIS.PAK.pakTCPOLRD.InsertData(_Rec)
    End Function
    Public Shared Function InsertData(ByVal Record As SIS.PAK.pakTCPOLRD) As SIS.PAK.pakTCPOLRD
      Using Con As SqlConnection = New SqlConnection(SIS.SYS.SQLDatabase.DBCommon.GetConnectionString())
        Using Cmd As SqlCommand = Con.CreateCommand()
          Cmd.CommandType = CommandType.StoredProcedure
          Cmd.CommandText = "sppakTCPOLRDInsert"
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@SerialNo",SqlDbType.Int,11, Record.SerialNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@ItemNo",SqlDbType.Int,11, Record.ItemNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@UploadNo",SqlDbType.Int,11, Record.UploadNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@DocumentID",SqlDbType.NVarChar,33, Iif(Record.DocumentID= "" ,Convert.DBNull, Record.DocumentID))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@DocumentRev",SqlDbType.NVarChar,21, Iif(Record.DocumentRev= "" ,Convert.DBNull, Record.DocumentRev))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@DocumentDescription",SqlDbType.NVarChar,101, Iif(Record.DocumentDescription= "" ,Convert.DBNull, Record.DocumentDescription))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@ReceiptNo",SqlDbType.NVarChar,10, Record.ReceiptNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@RevisionNo",SqlDbType.NVarChar,21, Record.RevisionNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@FileName",SqlDbType.NVarChar,101, Iif(Record.FileName= "" ,Convert.DBNull, Record.FileName))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@DiskFileName", SqlDbType.NVarChar, 251, IIf(Record.DiskFileName = "", Convert.DBNull, Record.DiskFileName))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@ERPDocSerialNo", SqlDbType.Int, 10, IIf(Record.ERPDocSerialNo = "", Convert.DBNull, Record.ERPDocSerialNo))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@AutoGenerated", SqlDbType.Bit, 3, Record.AutoGenerated)
          Cmd.Parameters.Add("@Return_SerialNo", SqlDbType.Int, 11)
          Cmd.Parameters("@Return_SerialNo").Direction = ParameterDirection.Output
          Cmd.Parameters.Add("@Return_ItemNo", SqlDbType.Int, 11)
          Cmd.Parameters("@Return_ItemNo").Direction = ParameterDirection.Output
          Cmd.Parameters.Add("@Return_UploadNo", SqlDbType.Int, 11)
          Cmd.Parameters("@Return_UploadNo").Direction = ParameterDirection.Output
          Cmd.Parameters.Add("@Return_DocSerialNo", SqlDbType.Int, 11)
          Cmd.Parameters("@Return_DocSerialNo").Direction = ParameterDirection.Output
          Con.Open()
          Cmd.ExecuteNonQuery()
          Record.SerialNo = Cmd.Parameters("@Return_SerialNo").Value
          Record.ItemNo = Cmd.Parameters("@Return_ItemNo").Value
          Record.UploadNo = Cmd.Parameters("@Return_UploadNo").Value
          Record.DocSerialNo = Cmd.Parameters("@Return_DocSerialNo").Value
        End Using
      End Using
      Return Record
    End Function
    <DataObjectMethod(DataObjectMethodType.Update, True)> _
    Public Shared Function pakTCPOLRDUpdate(ByVal Record As SIS.PAK.pakTCPOLRD) As SIS.PAK.pakTCPOLRD
      Dim _Rec As SIS.PAK.pakTCPOLRD = SIS.PAK.pakTCPOLRD.pakTCPOLRDGetByID(Record.SerialNo, Record.ItemNo, Record.UploadNo, Record.DocSerialNo)
      With _Rec
        .DocumentID = Record.DocumentID
        .DocumentRev = Record.DocumentRev
        .DocumentDescription = Record.DocumentDescription
        .ReceiptNo = Record.ReceiptNo
        .RevisionNo = Record.RevisionNo
        .FileName = Record.FileName
        .DiskFileName = Record.DiskFileName
        .ERPDocSerialNo = Record.ERPDocSerialNo
        .AutoGenerated = Record.AutoGenerated
      End With
      Return SIS.PAK.pakTCPOLRD.UpdateData(_Rec)
    End Function
    Public Shared Function UpdateData(ByVal Record As SIS.PAK.pakTCPOLRD) As SIS.PAK.pakTCPOLRD
      Using Con As SqlConnection = New SqlConnection(SIS.SYS.SQLDatabase.DBCommon.GetConnectionString())
        Using Cmd As SqlCommand = Con.CreateCommand()
          Cmd.CommandType = CommandType.StoredProcedure
          Cmd.CommandText = "sppakTCPOLRDUpdate"
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@Original_SerialNo",SqlDbType.Int,11, Record.SerialNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@Original_ItemNo",SqlDbType.Int,11, Record.ItemNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@Original_UploadNo",SqlDbType.Int,11, Record.UploadNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@Original_DocSerialNo",SqlDbType.Int,11, Record.DocSerialNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@SerialNo",SqlDbType.Int,11, Record.SerialNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@ItemNo",SqlDbType.Int,11, Record.ItemNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@UploadNo",SqlDbType.Int,11, Record.UploadNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@DocumentID",SqlDbType.NVarChar,33, Iif(Record.DocumentID= "" ,Convert.DBNull, Record.DocumentID))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@DocumentRev",SqlDbType.NVarChar,21, Iif(Record.DocumentRev= "" ,Convert.DBNull, Record.DocumentRev))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@DocumentDescription",SqlDbType.NVarChar,101, Iif(Record.DocumentDescription= "" ,Convert.DBNull, Record.DocumentDescription))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@ReceiptNo",SqlDbType.NVarChar,10, Record.ReceiptNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@RevisionNo",SqlDbType.NVarChar,21, Record.RevisionNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@FileName",SqlDbType.NVarChar,101, Iif(Record.FileName= "" ,Convert.DBNull, Record.FileName))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@DiskFileName",SqlDbType.NVarChar,251, Iif(Record.DiskFileName= "" ,Convert.DBNull, Record.DiskFileName))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@ERPDocSerialNo", SqlDbType.Int, 10, IIf(Record.ERPDocSerialNo = "", Convert.DBNull, Record.ERPDocSerialNo))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@AutoGenerated", SqlDbType.Bit, 3, Record.AutoGenerated)
          Cmd.Parameters.Add("@RowCount", SqlDbType.Int)
          Cmd.Parameters("@RowCount").Direction = ParameterDirection.Output
          _RecordCount = -1
          Con.Open()
          Cmd.ExecuteNonQuery()
          _RecordCount = Cmd.Parameters("@RowCount").Value
        End Using
      End Using
      Return Record
    End Function
    <DataObjectMethod(DataObjectMethodType.Delete, True)> _
    Public Shared Function pakTCPOLRDDelete(ByVal Record As SIS.PAK.pakTCPOLRD) As Int32
      Dim _Result as Integer = 0
      Using Con As SqlConnection = New SqlConnection(SIS.SYS.SQLDatabase.DBCommon.GetConnectionString())
        Using Cmd As SqlCommand = Con.CreateCommand()
          Cmd.CommandType = CommandType.StoredProcedure
          Cmd.CommandText = "sppakTCPOLRDDelete"
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@Original_SerialNo",SqlDbType.Int,Record.SerialNo.ToString.Length, Record.SerialNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@Original_ItemNo",SqlDbType.Int,Record.ItemNo.ToString.Length, Record.ItemNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@Original_UploadNo",SqlDbType.Int,Record.UploadNo.ToString.Length, Record.UploadNo)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@Original_DocSerialNo",SqlDbType.Int,Record.DocSerialNo.ToString.Length, Record.DocSerialNo)
          Cmd.Parameters.Add("@RowCount", SqlDbType.Int)
          Cmd.Parameters("@RowCount").Direction = ParameterDirection.Output
          _RecordCount = -1
          Con.Open()
          Cmd.ExecuteNonQuery()
          _RecordCount = Cmd.Parameters("@RowCount").Value
        End Using
      End Using
      Return _RecordCount
    End Function
'    Autocomplete Method
    Public Shared Function SelectpakTCPOLRDAutoCompleteList(ByVal Prefix As String, ByVal count As Integer, ByVal contextKey As String) As String()
      Dim Results As List(Of String) = Nothing
      Dim aVal() As String = contextKey.Split("|".ToCharArray)
      Using Con As SqlConnection = New SqlConnection(SIS.SYS.SQLDatabase.DBCommon.GetConnectionString())
        Using Cmd As SqlCommand = Con.CreateCommand()
          Cmd.CommandType = CommandType.StoredProcedure
          Cmd.CommandText = "sppakTCPOLRDAutoCompleteList"
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@LoginID", SqlDbType.NvarChar, 9, HttpContext.Current.Session("LoginID"))
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@prefix", SqlDbType.NVarChar, 50, Prefix)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@records", SqlDbType.Int, -1, count)
          SIS.SYS.SQLDatabase.DBCommon.AddDBParameter(Cmd, "@bycode", SqlDbType.Int, 1, IIf(IsNumeric(Prefix), 0, 1))
          Results = New List(Of String)()
          Con.Open()
          Dim Reader As SqlDataReader = Cmd.ExecuteReader()
          If Not Reader.HasRows Then
            Results.Add(AjaxControlToolkit.AutoCompleteExtender.CreateAutoCompleteItem("---Select Value---".PadRight(32, " "),"" & "|" & "" & "|" & "" & "|" & ""))
          End If
          While (Reader.Read())
            Dim Tmp As SIS.PAK.pakTCPOLRD = New SIS.PAK.pakTCPOLRD(Reader)
            Results.Add(AjaxControlToolkit.AutoCompleteExtender.CreateAutoCompleteItem(Tmp.DisplayField, Tmp.PrimaryKey))
          End While
          Reader.Close()
        End Using
      End Using
      Return Results.ToArray
    End Function
    Public Sub New(ByVal Reader As SqlDataReader)
      Try
        For Each pi As System.Reflection.PropertyInfo In Me.GetType.GetProperties
          If pi.MemberType = Reflection.MemberTypes.Property Then
            Try
              Dim Found As Boolean = False
              For I As Integer = 0 To Reader.FieldCount - 1
                If Reader.GetName(I).ToLower = pi.Name.ToLower Then
                  Found = True
                  Exit For
                End If
              Next
              If Found Then
                If Convert.IsDBNull(Reader(pi.Name)) Then
                  Select Case Reader.GetDataTypeName(Reader.GetOrdinal(pi.Name))
                    Case "decimal"
                      CallByName(Me, pi.Name, CallType.Let, "0.00")
                    Case "bit"
                      CallByName(Me, pi.Name, CallType.Let, Boolean.FalseString)
                    Case Else
                      CallByName(Me, pi.Name, CallType.Let, String.Empty)
                  End Select
                Else
                  CallByName(Me, pi.Name, CallType.Let, Reader(pi.Name))
                End If
              End If
            Catch ex As Exception
            End Try
          End If
        Next
      Catch ex As Exception
      End Try
    End Sub
    Public Sub New()
    End Sub
  End Class
End Namespace
